export default [
  {
    id: 1,
    picture: 'yuri.png',
    name: 'Yuri',
    nickname: 'Yuyu',
    personnality: {
      kind: true,
      power: "Fire",
      likes: 'loneliness',
      doesntLike: 'everyone',
      problem: 'burns everything',
    },
    met: 'in hell',
    isMortal: false,
  },
  {
    id: 2,
    picture: 'loser.png',
    name: 'Loser',
    nickname: 'Loverboy',
    personnality: {
      kind: false,
      power: "Eating himself ",
      likes: 'eating souls',
      doesntLike: 'noise',
      problem: 'is always craving for a soul',
    },
    met: 'in my nightmare',
    isMortal: false,
  },
  {
    id: 3,
    picture: 'shira.png',
    name: 'Shira',
    nickname: 'Big brain',
    personnality: {
      kind: true,
      power: 'Reading through minds',
      likes: 'psychology',
      doesntLike: 'dumb people',
      problem: 'always stares at people',
    },
    met: 'at hospital',
    isMortal: true,
  },
  {
    id: 4,
    picture: 'artyom.png',
    name: 'Artyom',
    nickname: 'Subway man',
    personnality: {
      kind: true,
      power: "The ability to survive",
      likes: 'good food',
      doesntLike: 'undergrounds',
      problem: "doesn't trust anyone",
    },
    met: 'in the subway',
    isMortal: true,
  },
  {
    id: 5,
    picture: 'joshua.png',
    name: 'Joshua',
    nickname: 'Jojo',
    personnality: {
      kind: true,
      power: 'Not having a mouth',
      likes: 'signing',
      doesntLike: 'babys',
      problem: 'is rotting from the inside',
    },
    met: 'in a cemetery',
    isMortal: true,
  },
]